// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnWbpdudhvhElEzYgCNKQCMW0bOHIBtxc',
    appId: '1:837452750041:web:12c7f9795054f977ae32c8',
    messagingSenderId: '837452750041',
    projectId: 'fanpager-be84e',
    authDomain: 'fanpager-be84e.firebaseapp.com',
    storageBucket: 'fanpager-be84e.appspot.com',
    measurementId: 'G-Q3PRBLHE3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBElbX0LmsFhQZgjVmYfSUl7awOo7e4mog',
    appId: '1:837452750041:android:c9991bf9a1e8e3cdae32c8',
    messagingSenderId: '837452750041',
    projectId: 'fanpager-be84e',
    storageBucket: 'fanpager-be84e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD57T67OC-JBDlSUSQ3tQaRapHs0GIGZ84',
    appId: '1:837452750041:ios:79117838fb60ca6dae32c8',
    messagingSenderId: '837452750041',
    projectId: 'fanpager-be84e',
    storageBucket: 'fanpager-be84e.appspot.com',
    iosClientId: '837452750041-j53hcjqcntucq6s4q5cmjdhcvb4okrot.apps.googleusercontent.com',
    iosBundleId: 'funpage.app',
  );
}
